baseURL = 'https://delgoodie.com'
languageCode = 'en-us'
title = 'delgoodie'
theme = 'hugo-PaperMod'

copyright = "delgoodie Â© 2025"

[markup]
[markup.highlight]
style = 'dracula'
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[caches]
[caches.images]
dir = ':cacheDir/images'


[params]
theme = "auto"
palette = "eink"
showThemeNotice = true
showPostsSummary = true


[[menu.main]]
identifier = "theory"
name = "âšœï¸Theory"
title = "âšœï¸Theory"
url = "/âšœï¸Theory"
weight = 3

[[menu.main]]
identifier = "experiement"
name = "ğŸ§ªExperiment"
title = "ğŸ§ªExperiment"
url = "/ğŸ§ªExperiment"
weight = 3


[[menu.main]]
identifier = "research"
name = "ğŸ§¬Research"
title = "ğŸ§¬Research"
url = "/ğŸ§¬Research"
weight = 3


[[menu.main]]
identifier = "recipe"
name = "ğŸ¥•Recipe"
title = "ğŸ¥•Recipe"
url = "/ğŸ¥•Recipe"
weight = 3

[[menu.main]]
identifier = "misc"
name = "ğŸ²Misc"
title = "ğŸ²Misc"
url = "/ğŸ²Misc"
weight = 3


[[menu.main]]
identifier = "posts"
name = "example"
title = "hugo example"
url = "/posts"
weight = 4

[[menu.main]]
identifier = "about"
name = "about"
title = "About"
url = "/about"
weight = 2

[[menu.main]]
identifier = "github"
name = "github"
title = "GitHub"
url = "https://github.com/delgoodie"
weight = 4
